version: "3.9"

services:
  service-a:
    build: ./service-a
    container_name: service-a
    ports:
      - "8081:8081"
    depends_on:
      - service-b
    networks:
      - microservices-network

  service-b:
    build: ./service-b
    container_name: service-b
    ports:
      - "8082:8082"
      - "9090:9090"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge